AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cx-dkbirpet-sam-echo

  The echo API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
  LambdaEchoSam:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.9
      Handler: app.handler
      CodeUri: ./src
      Events:
        PostEcho:
          Type: Api
          Properties:
            Path: /echo
            Method: post
        GetEcho:
          Type: Api
          Properties:
            Path: /echo
            Method: get
        GetEchos:
          Type: Api
          Properties:
            Path: /echo/{id}
            Method: get
        DeleteEcho:
          Type: Api
          Properties:
            Path: /echo/{id}
            Method: delete
Outputs:
    Lambdaechosamapi:
      Description: "API Gateway URL"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/echo"
    Function:
      Description: "LambdaEchoSam Arn"
      Value: !GetAtt LambdaEchoSam.Arn